KAFKA_BOOTSTRAP_SERVERS: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
KAFKA_SCHEMA_REGISTRY_URL: https://kafka-schema-registry.nais-q.adeo.no/

FAMILIE_INTEGRASJONER_API_URL: https://familie-integrasjoner.dev-fss-pub.nais.io
PDL_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default
STS_URL: https://api-gw-q1.oera.no/security-token-servic
