apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-personhendelse
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-personhendelse.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie-ef-personhendelse
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-lokal
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: dev-fss
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: familie-ef-proxy.dev-fss-pub.nais.io
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        databases:
          - name: familie-ef-personhendelse
            envVarPrefix: DB
            diskAutoresize: true
            tier: db-g1-small
            cascadingDelete: false